version: '3'

tasks:
    tools:
        cmds:
            # Install purego-gen
            - go install github.com/Zyko0/purego-gen/cmd/purego-gen@latest
    
    gen-ffi:        
        cmds:
            # Generate ffi.json files
            - docker build . -t sdl3ffi
            - docker create --name tmp sdl3ffi
            - docker cp tmp:/sdl_ffi.json ./cmd/internal/assets/ffi/sdl.json
            - docker cp tmp:/ttf_ffi.json ./cmd/internal/assets/ffi/ttf.json
            - docker cp tmp:/mixer_ffi.json ./cmd/internal/assets/ffi/mixer.json
            - docker rm -f tmp
    
    gen-bindings:
        deps: [tools, gen-ffi]
        requires:
            vars: [LIBRARY]
        vars:
            DIR: './{{if eq .LIBRARY "sdl"}}{{""}}{{else}}{{.LIBRARY}}{{end}}'
            INPUT:
                '{{.DIR}}/{{.LIBRARY}}_functions.gen.go'
            EXTRA:
                - '{{.DIR}}/{{.LIBRARY}}_structs.gen.go'
                - '{{.DIR}}/{{.LIBRARY}}_types.gen.go'
                - '{{.DIR}}/{{.LIBRARY}}_enums.gen.go'
                - '{{.DIR}}/extra.go'
        cmds:
            # Generate SDL3 bindings 
            - go run ./cmd/ffi2go --config "cmd/internal/assets/config/{{.LIBRARY}}.json" --ffi "cmd/internal/assets/ffi/{{.LIBRARY}}.json"
            - purego-gen --no-warnings --function-name "initialize" --input {{.INPUT}} --extra {{.EXTRA | join ","}}

    gen-methods:
        requires:
          vars: [LIBRARY]
        vars:
            DIR: './{{if eq .LIBRARY "sdl"}}{{""}}{{else}}{{.LIBRARY}}{{end}}'
        cmds:
            # Generate SDL3 methods heuristically as a starting point
            - go run ./cmd/methodgen --dir {{ .DIR }} --library {{ .LIBRARY }}