version: '3'

tasks:
    tools:
        cmds:
            # Install purego-gen
            - go install github.com/Zyko0/purego-gen/cmd/purego-gen@latest
    
    gen-ffi:        
        cmds:
            # Generate ffi.json files
            - docker build . -t sdl3ffi
            - docker create --name tmp sdl3ffi
            - docker cp tmp:/sdl_ffi.json ./cmd/internal/assets/ffi/sdl.json
            - docker cp tmp:/ttf_ffi.json ./cmd/internal/assets/ffi/ttf.json
            - docker cp tmp:/mixer_ffi.json ./cmd/internal/assets/ffi/mixer.json
            - docker cp tmp:/image_ffi.json ./cmd/internal/assets/ffi/img.json
            - docker rm -f tmp
    
    gen-bindings:
        deps: [tools, gen-ffi]
        requires:
            vars: [LIBRARY]
        vars:
            DIR: './{{if eq .LIBRARY "sdl"}}{{""}}{{else}}{{.LIBRARY}}{{end}}'
            INPUT:
                '{{.DIR}}/{{.LIBRARY}}_functions.gen.go'
            EXTRA:
                - '{{.DIR}}/{{.LIBRARY}}_structs.gen.go'
                - '{{.DIR}}/{{.LIBRARY}}_types.gen.go'
                - '{{.DIR}}/{{.LIBRARY}}_enums.gen.go'
                - '{{.DIR}}/glue.go'
        cmds:
            # Generate SDL3 bindings 
            - go run ./cmd/ffi2go --config "cmd/internal/assets/config/{{.LIBRARY}}.json" --ffi "cmd/internal/assets/ffi/{{.LIBRARY}}.json"
            - purego-gen --no-warnings --function-name "initialize" --input {{.INPUT}} --extra {{.EXTRA | join ","}}
            - '{{if eq .LIBRARY "ttf"}}purego-gen --no-warnings --function-name "initialize_ex" --input {{.DIR}}/{{.LIBRARY}}_functions_ex.go --extra {{.EXTRA | join ","}}{{end}}'

    gen-methods:
        requires:
          vars: [LIBRARY]
        vars:
            DIR: './{{if eq .LIBRARY "sdl"}}{{""}}{{else}}{{.LIBRARY}}{{end}}'
        cmds:
            # Generate SDL3 methods heuristically as a starting point
            - go run ./cmd/methodgen --dir {{ .DIR }} --library {{ .LIBRARY }}
    
    gen-doc:
        requires:
          vars: [LIBRARY]
        vars:
            DIR: './{{if eq .LIBRARY "sdl"}}{{""}}{{else}}{{.LIBRARY}}{{end}}'
        cmds:
            # Generate SDL3 documentation on top of functions
            - go run ./cmd/docgen --config "cmd/internal/assets/config/{{.LIBRARY}}.json" --dir {{ .DIR }}

    coverage:
        vars:
            INDICES: [0,1,2,3]
            LIBS: [sdl, ttf, img, mixer]
            DIRS: ['.', './ttf', './img', './mixer']
        cmds:
            - for:
                var: INDICES
              cmd: go run ./cmd/coverage --config "cmd/internal/assets/config/{{index .LIBS .ITEM}}.json" --dir {{index .DIRS .ITEM}}
    
    fmt:
        cmds:
            # go fmt code
            - go fmt github.com/Zyko0/go-sdl3/...